/**
 * One-shot seeder for the OSPREY threat register.
 * The YAML it writes is the source of truth from then on — edit those files.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../src/data/threats/', import.meta.url).pathname;
mkdirSync(ROOT, { recursive: true });

const str = (v) => (typeof v === 'boolean' || typeof v === 'number' ? String(v) : JSON.stringify(String(v)));
const yaml = (o, ind = 0) => {
  const pad = ' '.repeat(ind);
  return Object.entries(o).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => {
    if (Array.isArray(v)) {
      if (v.length === 0) return `${pad}${k}: []`;
      return `${pad}${k}:\n` + v.map((i) =>
        typeof i === 'object' ? `${pad}  -\n${yaml(i, ind + 4)}` : `${pad}  - ${str(i)}`).join('\n');
    }
    if (typeof v === 'object') return `${pad}${k}:\n${yaml(v, ind + 2)}`;
    return `${pad}${k}: ${str(v)}`;
  }).join('\n');
};

const V = '2026-09-03';
const a = (framework, id, label, rationale, verification = 'verified', weight = 'primary') =>
  ({ framework, id, label, weight, rationale, verification, checked: V });

const T = [
{
  slug: 'osp-01', code: 'OSP-01', name: 'Intent / Goal Drift', order: 1, scope: 'core',
  behaviour: 'The agent gradually stops working on the task it was given. It still looks busy and may report progress, but its actions aim at something other than the original objective. Drift can be induced by an attacker or emerge on its own from a long, messy session.',
  signals: [
    'Trajectory embedding distance from the task baseline exceeds threshold',
    'Tool calls unrelated to the declared task',
    'A widening gap between the agent’s stated plan and its executed actions',
    'Session step count well above baseline for that task type',
    'Repeated re-planning with no progress toward the declared goal',
  ],
  severity: 'high',
  harmClasses: ['operational', 'systemic'],
  harmNote: 'Operational while contained to one agent; systemic once a drifting agent’s output is consumed downstream.',
  action: { peak: 'quarantine', summary: 'Monitor continuously. Review at moderate drift, quarantine at high drift.', tier: 'HITL', humanReview: 'conditional', reviewNote: 'Drops the agent to HOTL at Review and HITL at Quarantine. Human review is required above the quarantine threshold.' },
  detection: { instrument: 'embedding-scorer', method: 'Embedding distance over the session trajectory, with a per-task-type baseline', slmDifficulty: 'hard',
    rationale: 'Not a classification problem. It is a continuous distance score over a trajectory, needing a baseline per task type rather than a labelled example per instance. A model can name the drift once flagged, but the flag itself comes from the scorer.',
    inGate1: false, dependsOn: ['Full tool-call sequence per session', 'Declared task objective at session start'] },
  evidence: ['Expected-behaviour baseline and abnormal-behaviour criteria (AGSC SAF-01)', 'Alert records against defined thresholds (ADG MC-8)'],
  anchors: [
    a('agsc', 'SAF-01', 'Autonomous System Oversight', 'The control exists to catch an agent operating outside its expected behaviour without anyone watching.'),
    a('agsc', 'ALN-01', 'Autonomy Boundary Control', 'Drift is the boundary being approached from the inside rather than breached from the outside.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Drift is named in this control’s scope alongside abuse and configuration drift.'),
    a('adg', 'MC-2', 'Risk Classification', 'The autonomy tier a detection downgrades is the tier this control assigns.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'Excessive autonomy is one of the three named root causes, and drift is how it manifests over a long session.'),
    a('owasp-llm', 'LLM07', 'Misinformation', 'Incorrect state inference in workflows: the agent believes a condition was met when it was not.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI01', 'Agent Goal Hijack', 'Adversarially induced drift is precisely goal hijack.'),
    a('owasp-asi', 'ASI10', 'Rogue Agents', 'Sustained off-task operation with reported success matches the rogue-agent failure mode.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.TA0014', 'Command and Control', 'Sustained adversarial control of an agent’s objective is a C2 relationship.'),
    a('mitre-atlas', 'AML.T0051', 'LLM Prompt Injection', 'The delivery mechanism for adversarially induced drift.', 'verified', 'supporting'),
    { framework: 'mitre-atlas', id: '—', label: 'Emergent drift', weight: 'primary', verification: 'gap',
      rationale: 'No published ATLAS technique models drift that emerges without an adversary. The AGSC and ADG controls carry this case on their own.' },
  ],
  regulatory: ['EU AI Act Art. 14, 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.6.2, A.9'],
},
{
  slug: 'osp-02', code: 'OSP-02', name: 'Direct Prompt Injection', order: 2, scope: 'core',
  behaviour: 'A user or upstream caller embeds instructions in their input that override the agent’s system prompt or assigned task. The agent follows the injected instruction instead of its own.',
  signals: [
    'Instruction-shaped text in user-supplied fields',
    'References to the system prompt, or "ignore previous" patterns',
    'The agent’s declared objective changing immediately after a user input event',
    'Obfuscated encodings — base64, invisible Unicode, low-resource language — in user fields',
  ],
  severity: 'high',
  harmClasses: ['technical'],
  action: { peak: 'block', summary: 'Block at input on high confidence. Escalate ambiguous cases to the frontier escalation layer rather than auto-resolving.', tier: 'HOTL', humanReview: 'no', reviewNote: 'No human needed for a clean block. The agent runs at HOTL for the remainder of the session, and repeat attempts against the same agent escalate to review.' },
  detection: { instrument: 'slm-classifier', method: 'Fine-tuned SLM classifier over the input span', slmDifficulty: 'easy',
    rationale: 'The closest thing in the register to a standard text-classification task. Single input, plentiful synthetic examples, clear positive class. The label most likely to hit its target first, and the right anchor for the first evaluation gate.',
    inGate1: true, dependsOn: ['Input span capture with field attribution'] },
  evidence: ['Injection detection results and blocked-input records (AGSC SEC-03)', 'Adversarial test results (ADG MC-4)'],
  anchors: [
    a('agsc', 'SEC-03', 'Prompt Injection & Adversarial Input Defense', 'The control this label exists to provide evidence for.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Blocked-input records are monitoring evidence with a defined threshold.'),
    a('adg', 'MC-4', 'Pre-Production Evaluation', 'Injection testing before go-live is part of this control’s signed report.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM01', 'Prompt Injection', 'The direct-delivery half of the 2026 entry, which holds the top rank on the strength of the community vote.'),
    a('owasp-asi', 'ASI01', 'Agent Goal Hijack', 'Injected input overrides the system-prompt role and capability constraints, redirecting agent goals.'),
    a('owasp-asi', 'ASI02', 'Tool Misuse & Exploitation', 'Injected input drives unauthorized tool invocation.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.T0051', 'LLM Prompt Injection', 'The technique this category is named after.'),
    a('mitre-atlas', 'AML.TA0004', 'Initial Access', 'Injected instructions are the foothold that lets an attacker seize control of model behaviour.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.TA0007', 'Defense Evasion', 'Obfuscated encodings and jailbreak phrasing slip past safety filters.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MEASURE 2.7', 'ISO/IEC 42001 A.6.2'],
},
{
  slug: 'osp-03', code: 'OSP-03', name: 'Indirect / Context Poisoning', order: 3, scope: 'core',
  behaviour: 'Malicious instructions reach the agent through content it reads rather than from the user: a retrieved document, a web page, a tool response, or its own long-term memory. The agent treats that content as trusted context.',
  signals: [
    'Instruction-shaped text inside retrieved documents or tool outputs',
    'Behaviour change immediately following a retrieval event',
    'Writes to long-term memory containing directives rather than facts',
    'Instructions whose execution is conditioned on a later turn or date',
    'A single document dominating retrieval results for a query',
  ],
  severity: 'high',
  harmClasses: ['technical', 'systemic'],
  harmNote: 'Becomes systemic the moment a poisoned write persists: every later session that reads the store inherits it.',
  action: { peak: 'quarantine', summary: 'Quarantine the poisoned context and block the memory write. Escalate to the frontier layer when the classification is ambiguous.', tier: 'HITL', humanReview: 'always', reviewNote: 'Required. A poisoned memory write persists across every later session, so the write approval cannot be automated away.' },
  detection: { instrument: 'hybrid', method: 'SLM classifier over the span, gated by a provenance rule', slmDifficulty: 'medium',
    rationale: 'The text classification resembles OSP-02, but the hard part is provenance: knowing a span came from a retrieved document rather than the user. That is a telemetry field, not a model capability. Without it the model is guessing.',
    inGate1: true, dependsOn: ['Span-level provenance (user / retrieval / tool / memory)', 'Memory write interception'] },
  evidence: ['Input provenance records (AGSC GOV-01)', 'Memory-write decisions (AGSC SEC-07)', 'Context policy conformance (ADG MC-6)'],
  anchors: [
    a('agsc', 'SEC-03', 'Prompt Injection & Adversarial Input Defense', 'The control explicitly covers instructions hidden in untrusted external content.'),
    a('agsc', 'SEC-07', 'Memory & Context Lifecycle Security', 'Poisoned context that persists is a memory-lifecycle failure.'),
    a('agsc', 'GOV-01', 'Data Provenance & Input Integrity', 'The provenance field this control establishes is what makes the label detectable at all.', 'verified', 'supporting'),
    a('adg', 'MC-6', 'Context Policy', 'Trust ordering across context inputs is exactly what this attack subverts.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Detection and alerting on poisoned retrieval.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM01', 'Prompt Injection', 'The indirect-delivery half: injection arriving through retrieved content or tool output.'),
    a('owasp-llm', 'LLM05', 'Data and Model Poisoning', 'Covers RAG knowledge-base poisoning and persistent agent-memory poisoning across sessions.'),
    a('owasp-llm', 'LLM09', 'Vector and Embedding Weaknesses', 'Where the attack exploits retrieval geometry rather than instruction-following.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI06', 'Memory & Context Poisoning', 'The direct agentic counterpart.'),
    a('mitre-atlas', 'AML.T0070', 'RAG Poisoning', 'Poisoning the retrieval corpus so malicious content surfaces for a targeted query.'),
    a('mitre-atlas', 'AML.T0080', 'AI Agent Context Poisoning', 'Poisoning the agent’s working context directly.'),
    a('mitre-atlas', 'AML.T0099', 'AI Agent Tool Data Poisoning', 'Placing malicious content where agent tools will retrieve it.'),
    a('mitre-atlas', 'AML.T0093', 'Prompt Infiltration via Public-Facing Application', 'Delivery through a public surface the agent later ingests.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.TA0006', 'Persistence', 'Injected instructions written to memory survive across sessions and re-fire on recall.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 10, 15', 'NIST AI RMF MEASURE 2.7; MAP 2', 'ISO/IEC 42001 A.6.2, A.7'],
},
{
  slug: 'osp-04', code: 'OSP-04', name: 'Tool-Chain Exploitation', order: 4, scope: 'core',
  behaviour: 'Individually legitimate tools are chained into a harmful outcome. Each call passes its own permission check, but the sequence does something no single call would be allowed to do — reading a secret with one tool and transmitting it with another.',
  signals: [
    'Tool-call sequences absent from the learned baseline',
    'Read-then-transmit patterns across different tools',
    'Unusual argument values passed between calls',
    'Call depth or recursion above baseline',
    'A tool output becoming the next call’s argument with no validation step between',
  ],
  severity: 'high',
  harmClasses: ['technical'],
  action: { peak: 'quarantine', summary: 'Quarantine the session and pause the pipeline through the Harness policy gate.', tier: 'HITL', humanReview: 'always', reviewNote: 'Required before the session resumes. The chain has to be read by a person, because what makes it malicious is the combination rather than any one call.' },
  detection: { instrument: 'sequence-model', method: 'Sequence model over the call trajectory, with rule coverage of known-bad shapes first', slmDifficulty: 'hard',
    rationale: 'The malicious unit is the sequence, not any single call. Needs the full trajectory as input and a baseline of normal sequences. Expect rule coverage of known-bad patterns first and model coverage later.',
    inGate1: false, dependsOn: ['Full tool-call sequence per session', 'Argument capture per call'] },
  evidence: ['Autonomy-boundary enforcement records: which chains were permitted, which were stopped (AGSC ALN-01)', 'Per-tool invocation policy evidence (ADG MC-7)'],
  anchors: [
    a('agsc', 'ALN-01', 'Autonomy Boundary Control', 'The boundary is defined over the action space, which is what a chain traverses.'),
    a('agsc', 'SEC-01', 'Multi-Agent Coordination Security', 'Chains that cross agents inherit this control too.', 'verified', 'supporting'),
    a('adg', 'MC-7', 'Tool and MCP Register', 'Per-invocation policy evaluation is the control that a chain defeats one call at a time.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Unsafe actions in production are named in scope.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'Excessive functionality and excessive permissions are two of the three named root causes.'),
    a('owasp-asi', 'ASI02', 'Tool Misuse & Exploitation', 'The direct agentic counterpart, including the "lethal trifecta" conditions.'),
    a('mitre-atlas', 'AML.T0053', 'AI Agent Tool Invocation', 'Invocation of agent tools toward an adversary objective.'),
    a('mitre-atlas', 'AML.TA0005', 'Execution', 'A successful chain drives the agent to run adversary-chosen operations.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 14, 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.9'],
},
{
  slug: 'osp-05', code: 'OSP-05', name: 'Privilege & Identity Abuse', order: 5, scope: 'core',
  behaviour: 'The agent acts with credentials or scopes broader than its task needs, or borrows a human’s identity to perform something that human never approved. Includes long-lived tokens used well beyond their intended session.',
  signals: [
    'Calls to tools outside the agent’s declared scope',
    'Use of long-lived or shared tokens',
    'Credential-read events',
    'Role or scope escalation partway through a call chain',
    'One service account serving several agent identities',
  ],
  severity: 'critical',
  harmClasses: ['technical'],
  action: { peak: 'quarantine', summary: 'Block and quarantine immediately. A deterministic check against the declared scope, not a model decision.', tier: 'HITL', humanReview: 'always', reviewNote: 'Always, with no exceptions. This is the control that proves every agent action traces back to a human authority, so an automated dismissal would defeat its purpose.' },
  detection: { instrument: 'deterministic', method: 'Lookup against the agent identity register and declared scope', slmDifficulty: null,
    rationale: 'Should never be a model decision. Comparing a call against a declared scope is a lookup. Routing it through a classifier would add false negatives to something that can be exact.',
    inGate1: false, dependsOn: ['Machine-readable declared scope per agent', 'Agent identity register'] },
  evidence: ['Agent identity register and least-privilege authorization decisions (AGSC SEC-02)', 'Inventory entries with named owner (ADG MC-1)'],
  anchors: [
    a('agsc', 'SEC-02', 'Agent Identity & Least-Privilege Authorization', 'This label is the runtime enforcement of that control.'),
    a('adg', 'MC-1', 'AI System Inventory', 'The register checked against is the artifact this control requires.'),
    a('adg', 'MC-3', 'Separation of Duties', 'An agent authorising its own privileged action collapses the separation.', 'verified', 'supporting'),
    a('adg', 'MC-7', 'Tool and MCP Register', 'Scope is expressed per tool in the register.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'Excessive permissions — the tool connects with an identity holding more rights than the task needs.'),
    a('owasp-asi', 'ASI03', 'Identity & Privilege Abuse', 'The direct agentic counterpart.'),
    a('mitre-atlas', 'AML.T0055', 'Unsecured Credentials', 'Credentials reachable by the agent that should not be.'),
    a('mitre-atlas', 'AML.TA0012', 'Privilege Escalation', 'An agent on a trusted backend acting under elevated credentials.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.TA0013', 'Credential Access', 'Credential-read events are the enabling step.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MANAGE 2.x', 'ISO/IEC 42001 A.9 (with ISO/IEC 27001)'],
},
{
  slug: 'osp-06', code: 'OSP-06', name: 'Anomalous Tool Misuse', order: 6, scope: 'core',
  behaviour: 'One tool used in a way that is technically permitted but statistically abnormal for this agent and task: a bulk delete, an oversized export, a destructive call outside a change window.',
  signals: [
    'Argument-value outliers against the learned baseline',
    'Call volume or rate spikes',
    'Destructive verbs — delete, drop, revoke, purge — outside approved windows',
    'Result-set sizes far above the task envelope',
  ],
  severity: 'medium-high',
  harmClasses: ['operational', 'technical'],
  harmNote: 'Operational for most outliers; technical once the call is destructive or exfiltrating.',
  action: { peak: 'review', summary: 'Review. Hold destructive actions for explicit confirmation before execution.', tier: 'HOTL', humanReview: 'conditional', reviewNote: 'HOTL by default. Any destructive verb escalates to HITL and waits for confirmation rather than executing and alerting afterwards.' },
  detection: { instrument: 'statistical', method: 'Argument and rate outlier detection against a per-agent, per-task baseline', slmDifficulty: 'medium',
    rationale: 'Argument-value and rate outliers are a statistics problem. A model adds value only in judging whether an outlier is contextually justified — an escalation-layer question, not first-pass classification.',
    inGate1: false, dependsOn: ['Argument capture per call', 'Per-agent call-rate baseline'] },
  evidence: ['Anomaly detection logs and alert records (AGSC SEC-04)', 'Defined alert thresholds and response SLAs (ADG MC-8)'],
  anchors: [
    a('agsc', 'SEC-04', 'Observability, Anomaly Detection & Incident Response', 'The control that names abnormal behaviour and unexpected agent activity as its detection target.'),
    a('agsc', 'ALN-01', 'Autonomy Boundary Control', 'A permitted-but-abnormal call sits just inside the boundary.', 'verified', 'supporting'),
    a('adg', 'MC-7', 'Tool and MCP Register', 'Trust tiering per tool is what makes "abnormal for this tool" meaningful.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Abuse detection in production.'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'Impacts span confidentiality, integrity and availability depending on what the tool reaches.'),
    a('owasp-asi', 'ASI02', 'Tool Misuse & Exploitation', 'The direct agentic counterpart.'),
    a('mitre-atlas', 'AML.T0053', 'AI Agent Tool Invocation', 'Invocation is the observable event; abnormality is the judgement layered on it.'),
    a('mitre-atlas', 'AML.TA0011', 'Impact', 'Destructive calls land here.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 12, 15', 'NIST AI RMF MEASURE 2.x', 'ISO/IEC 42001 A.9'],
},
{
  slug: 'osp-07', code: 'OSP-07', name: 'Unsafe Output & Code Execution', order: 7, scope: 'core',
  behaviour: 'The agent generates output that is executed or acted on downstream without validation, turning generated text into running code, a live query, or a rendered document.',
  signals: [
    'Code blocks routed directly to execution tools',
    'Shell, SQL or template-injection patterns in outputs',
    'Execution calls not preceded by a validation step',
    'ANSI or control characters written to terminal, log or IDE sinks',
    'Auto-fetched external resources such as markdown image URLs in rendered output',
  ],
  severity: 'high',
  harmClasses: ['technical'],
  action: { peak: 'block', summary: 'Block execution pending validation. Quarantine when the pattern matches a known exploit shape.', tier: 'HITL', humanReview: 'conditional', reviewNote: 'The block itself is automatic and needs no human. Releasing a blocked execution requires HITL approval.' },
  detection: { instrument: 'hybrid', method: 'Static pattern check for known shapes, SLM classifier for obfuscated or novel payloads', slmDifficulty: 'medium',
    rationale: 'Pattern matching catches the obvious cases cheaply. The model is needed for obfuscated or novel payloads — exactly where labelled data will be thinnest.',
    inGate1: true, dependsOn: ['Output capture before the downstream sink', 'Sink type attribution (shell / SQL / renderer)'] },
  evidence: ['Output-safeguard decisions and blocked-execution records (AGSC SAF-05)', 'Release-gate verification (ADG MC-4)'],
  anchors: [
    a('agsc', 'SAF-05', 'AI Output Monitoring & Safeguards', 'Safeguards that block risky outputs before they create harm.'),
    a('agsc', 'SEC-03', 'Prompt Injection & Adversarial Input Defense', 'Injection is the usual upstream cause of a weaponised output.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Unsafe actions in production.'),
    a('adg', 'MC-4', 'Pre-Production Evaluation', 'Failure-mode testing before go-live.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM10', 'Improper Output Handling', 'The entry that owns insufficient validation of model output before it reaches a downstream component.'),
    a('owasp-llm', 'LLM01', 'Prompt Injection', 'Injection is what makes the output attacker-controlled in the first place.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI05', 'Unexpected Code Execution (RCE)', 'The direct agentic counterpart.'),
    a('mitre-atlas', 'AML.TA0005', 'Execution', 'Generated content becoming a running command.'),
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MEASURE 2.x; MANAGE 4.1', 'ISO/IEC 42001 A.6.2'],
},
{
  slug: 'osp-13', code: 'OSP-13', name: 'Sandbox / Host Escape', order: 8, scope: 'core',
  behaviour: 'The agent’s execution environment stops holding. Code the agent runs breaks out of its sandbox onto the host, or reaches machine resources and artifacts the agent was never scoped to touch.',
  signals: [
    'Process or filesystem activity outside the sandbox mount',
    'Container runtime or hypervisor API calls from agent-executed code',
    'Reads of local model artifacts or credentials on the host',
    'Egress from the execution sandbox to internal networks',
  ],
  severity: 'critical',
  harmClasses: ['technical', 'systemic'],
  harmNote: 'Systemic once the host is reached: everything else running on that machine is in scope.',
  action: { peak: 'kill', summary: 'Kill the execution environment and quarantine the agent session. A deterministic runtime check, not a model decision.', tier: 'HITL', humanReview: 'always', reviewNote: 'Always. Restart requires formal approval plus a forensic replay of the session that produced the escape.' },
  detection: { instrument: 'deterministic', method: 'Runtime boundary events from the sandbox and container layer', slmDifficulty: null,
    rationale: 'A boundary violation is observable at the runtime layer. Sandbox egress, host process activity and container API calls are facts, not judgements. Asking a classifier to infer them would be strictly worse than reading them.',
    inGate1: false, dependsOn: ['Container and host-boundary event stream', 'Sandbox egress logging'] },
  evidence: ['Containment activation records and recovery evidence (AGSC SAF-02)', 'Replayable incident evidence capture (ADG MC-9)'],
  anchors: [
    a('agsc', 'SAF-02', 'Emergency Stop & Containment (Kill Switch)', 'This is the category that most directly exercises the kill switch.'),
    a('agsc', 'SEC-02', 'Agent Identity & Least-Privilege Authorization', 'Host reach is privilege escalation past the declared scope.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Configuration and boundary drift in production.'),
    a('adg', 'MC-9', 'AI Incident Response', 'A confirmed escape is an incident with forensic-replay obligations.'),
    a('owasp-llm', 'LLM10', 'Improper Output Handling', 'Unvalidated generated code reaching a shell is the usual path.'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'A shell-command tool that fails to filter unintended commands.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI05', 'Unexpected Code Execution (RCE)', 'File-system and cloud-API access turning execution into host compromise.'),
    a('mitre-atlas', 'AML.TA0005', 'Execution', 'Adversary-chosen code running on the host.'),
    a('mitre-atlas', 'AML.TA0012', 'Privilege Escalation', 'Crossing the sandbox boundary is escalation by definition.'),
    { framework: 'mitre-atlas', id: 'AML.T0097 / T0105 / T0112', label: 'Sandbox evasion, escape to host, machine compromise',
      weight: 'supporting', verification: 'pending',
      rationale: 'Technique identifiers carried from an earlier revision. Not re-confirmed against a reachable ATLAS source in the latest validation pass — confirm before external citation.' },
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.6.2, A.9'],
},
{
  slug: 'osp-14', code: 'OSP-14', name: 'Resource Exhaustion & Denial of Wallet', order: 9, scope: 'core', addedIn: 'v1.0',
  behaviour: 'The agent consumes compute, tokens or spend far beyond what the task warrants — a reasoning loop that will not terminate, a retry storm, or a tool-call fan-out where one request becomes hundreds. No single call looks wrong; the damage is the aggregate.',
  signals: [
    'Thinking or output token spend per session far above baseline for the task type',
    'Non-terminating reasoning loops',
    'Tool-call fan-out ratio above threshold',
    'Retry counts with no state change between attempts',
    'Sustained near-context-limit requests',
    'Session cost breaching its budget envelope',
  ],
  severity: 'medium-high',
  severityNote: 'High where spend is uncapped, because the ceiling on the loss is set by the billing account rather than by the system.',
  harmClasses: ['operational', 'technical'],
  action: { peak: 'block', summary: 'Monitor against a hard budget ceiling. Review on breach; circuit-break the loop at the hard cap.', tier: 'HOTL', humanReview: 'conditional', reviewNote: 'The circuit-break is automatic. HOTL authorises a restart; a second breach in the same workflow escalates to HITL.' },
  detection: { instrument: 'statistical', method: 'Budget counters and fan-out thresholds per session', slmDifficulty: null,
    rationale: 'Token spend, fan-out ratio, retry count and session cost are counters. A model asked to judge them would be slower, more expensive and less accurate than the arithmetic. The circuit breaker is the control; the model has no first-pass role.',
    inGate1: false, dependsOn: ['Per-session token and cost telemetry', 'Tool-call fan-out counters'] },
  evidence: ['Cost and consumption telemetry with breach records (AGSC SEC-04, GOV-08)', 'Retry-budget and recursion-limit evidence (ADG MC-8)'],
  anchors: [
    a('agsc', 'SEC-04', 'Observability, Anomaly Detection & Incident Response', 'Abnormal consumption is an anomaly with a defined threshold.'),
    a('agsc', 'SAF-02', 'Emergency Stop & Containment (Kill Switch)', 'The circuit breaker is a scoped kill switch.', 'verified', 'supporting'),
    a('agsc', 'GOV-08', 'Environmental & Carbon Governance', 'The same counters serve efficiency reporting.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Abuse detection with defined alert thresholds.'),
    a('owasp-llm', 'LLM06', 'Unbounded Consumption', 'The entry that rose four places in 2026, covering denial of wallet, reasoning-loop exhaustion and MCP fan-out.'),
    a('owasp-asi', 'ASI02', 'Tool Misuse & Exploitation', 'Agent-tool loops and MCP fan-out drive recursive high-volume calls.'),
    a('owasp-asi', 'ASI08', 'Cascading Failures', 'Agentic architectures amplify a single request into cascading downstream operations.'),
    a('mitre-atlas', 'AML.T0034', 'Cost Harvesting', 'Driving expensive computation at the victim’s expense.'),
    a('mitre-atlas', 'AML.TA0011', 'Impact', 'Availability and cost harm.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.6.2'],
},

/* ---------- secondary scope ---------- */
{
  slug: 'osp-08', code: 'OSP-08', name: 'Sensitive Data Exposure', order: 10, scope: 'secondary',
  behaviour: 'The agent surfaces or transmits data the requester is not entitled to — PII, secrets, or cross-tenant content — through its output, its memory, its tool-call arguments, or its reasoning trace.',
  signals: [
    'PII or secret patterns in agent output or tool-call arguments',
    'Cross-tenant identifiers appearing in a single session',
    'Memory reads returning content from another user’s context',
    'Outbound calls carrying regulated fields',
    'Embeddings or vector-store backups leaving the trust boundary',
  ],
  severity: 'high',
  harmClasses: ['technical', 'societal'],
  harmNote: 'Societal because the harm lands on data subjects who were never party to the session.',
  action: { peak: 'quarantine', summary: 'Quarantine the output, redact, and log as a potentially reportable event.', tier: 'HITL', humanReview: 'always', reviewNote: 'Required. The incident record has to be complete enough to support a reporting decision under whichever regime applies.' },
  detection: { instrument: 'hybrid', method: 'Pattern matching and entity detection, with a model for unstructured disclosure', slmDifficulty: 'medium',
    rationale: 'Regex and entity detection handle structured secrets well. The residual model problem is unstructured disclosure and cross-tenant leakage in paraphrase, which is where labels are hardest to source.',
    inGate1: true, dependsOn: ['Output and tool-argument capture', 'Tenant attribution per session'] },
  evidence: ['Memory and context lifecycle records; redaction decisions (AGSC SEC-07)', 'Incident evidence pack (ADG MC-9)'],
  anchors: [
    a('agsc', 'SEC-07', 'Memory & Context Lifecycle Security', 'Cross-user and cross-session leakage is the failure this control prevents.'),
    a('agsc', 'SAF-05', 'AI Output Monitoring & Safeguards', 'Blocking a disclosing output before it lands.', 'verified', 'supporting'),
    a('adg', 'MC-6', 'Context Policy', 'Redaction rules and data-class handling.'),
    a('adg', 'MC-9', 'AI Incident Response', 'Reportable events need replayable evidence.'),
    a('owasp-llm', 'LLM02', 'Sensitive Information Disclosure', 'The 2026 entry explicitly widens the disclosure surface to tool-call arguments, reasoning traces and telemetry.'),
    a('owasp-llm', 'LLM09', 'Vector and Embedding Weaknesses', 'Cross-tenant retrieval and embedding inversion are recognised leak paths.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI06', 'Memory & Context Poisoning', 'Persistent agent memory leading to cross-session data leakage.'),
    a('mitre-atlas', 'AML.T0057', 'LLM Data Leakage', 'Data leaving the system through the model.'),
    a('mitre-atlas', 'AML.TA0010', 'Exfiltration', 'The tactic the leak serves.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 10, 12, 15', 'NIST AI RMF MANAGE 2.x', 'ISO/IEC 42001 A.7'],
},
{
  slug: 'osp-09', code: 'OSP-09', name: 'Inter-Agent Trust Abuse', order: 11, scope: 'secondary',
  behaviour: 'In a multi-agent pipeline, one agent accepts instructions or results from another without verifying who sent them or whether that agent was entitled to ask.',
  signals: [
    'Unauthenticated inter-agent messages',
    'Delegation to an agent outside the declared topology',
    'An agent identity appearing that was not registered for the workflow',
    'Guardrail configuration mismatch between two communicating agents',
  ],
  severity: 'medium',
  severityNote: 'Rises to High once multi-agent topologies reach production, where an unverified delegation reaches real systems.',
  harmClasses: ['systemic'],
  action: { peak: 'monitor', summary: 'Monitor for now. Moves to quarantine scope once multi-agent topologies are in production.', tier: 'HOOTL', humanReview: 'no', reviewNote: 'Not while the category sits at Monitor. The tier tightens to HOTL when it moves to quarantine scope.' },
  detection: { instrument: 'deterministic', method: 'Protocol and authentication check against the declared topology', slmDifficulty: null,
    rationale: 'Whether an inter-agent message was authenticated is a protocol fact. A model has no role until the question becomes whether a legitimate delegation was appropriate.',
    inGate1: false, dependsOn: ['Declared agent topology', 'Inter-agent message authentication'] },
  evidence: ['Inter-agent authorization records and topology register (AGSC SEC-01)', 'RACI conformance (ADG MC-3)'],
  anchors: [
    a('agsc', 'SEC-01', 'Multi-Agent Coordination Security', 'Agent roles, communication paths and escalation rules are exactly what this label checks.'),
    a('adg', 'MC-3', 'Separation of Duties', 'An agent should not be able to authorise its own delegation.'),
    a('adg', 'MC-7', 'Tool and MCP Register', 'Cross-agent capability access is registered like any other capability.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM03', 'Excessive Agency', 'Authorization scope must be preserved across chained agent calls.'),
    a('owasp-asi', 'ASI07', 'Insecure Inter-Agent Communication', 'The direct agentic counterpart.'),
    a('mitre-atlas', 'AML.TA0008', 'Discovery', 'Enumerating the agent topology precedes abusing it.', 'verified', 'supporting'),
    { framework: 'mitre-atlas', id: 'AML.T0103 / T0108', label: 'Agent deployment and agent-as-technique entries',
      weight: 'supporting', verification: 'pending',
      rationale: 'Identifiers carried from an earlier revision and not re-confirmed in the latest validation pass.' },
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.6.2'],
},
{
  slug: 'osp-10', code: 'OSP-10', name: 'Cascading Failure', order: 12, scope: 'secondary',
  behaviour: 'One agent’s bad output becomes another agent’s trusted input, and a single fault or compromise propagates across the pipeline faster than a human can intervene.',
  signals: [
    'Correlated anomaly scores across linked sessions',
    'The same malformed artifact appearing in successive stages',
    'Retry storms across a workflow',
    'A spike in downstream failures within one workflow',
  ],
  severity: 'medium-high',
  harmClasses: ['systemic'],
  action: { peak: 'quarantine', summary: 'Quarantine the whole workflow, not just the failing agent.', tier: 'HITL', humanReview: 'always', reviewNote: 'Required before any stage of the workflow restarts, because restarting the failing agent alone re-feeds the same bad artifact downstream.' },
  detection: { instrument: 'derived', method: 'Correlation over per-agent anomaly scores across a workflow', slmDifficulty: null,
    rationale: 'Computed from other detectors rather than observed directly. It is a correlation over per-agent anomaly scores across a workflow, so it cannot be a classifier label — there is no single input to classify.',
    inGate1: false, dependsOn: ['Workflow correlation id across sessions', 'Per-agent anomaly scores'] },
  evidence: ['Workflow-level containment records (AGSC SAF-02)', 'Incident evidence pack and governance review inputs (ADG MC-9, MC-10)'],
  anchors: [
    a('agsc', 'SEC-01', 'Multi-Agent Coordination Security', 'Safeguards for loops, deadlocks and cascading actions are named in the control.'),
    a('agsc', 'SAF-01', 'Autonomous System Oversight', 'The workflow as a whole is the autonomous system under oversight.', 'verified', 'supporting'),
    a('agsc', 'SAF-02', 'Emergency Stop & Containment (Kill Switch)', 'Containment has to reach the workflow, not just the agent.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Cross-surface anomaly correlation.'),
    a('adg', 'MC-9', 'AI Incident Response', 'A cascade is a multi-system incident.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM07', 'Misinformation', 'Cross-agent misinformation propagation: incorrect state produced by one agent and trusted by another.'),
    a('owasp-llm', 'LLM06', 'Unbounded Consumption', 'Retry storms and fan-out amplify the cascade.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI08', 'Cascading Failures', 'The direct agentic counterpart.'),
    { framework: 'mitre-atlas', id: '—', label: 'Cross-agent fault propagation', weight: 'primary', verification: 'gap',
      rationale: 'No published ATLAS technique models a fault propagating across agents. The AGSC and ADG controls carry this row on their own.' },
  ],
  regulatory: ['EU AI Act Art. 14, 15', 'NIST AI RMF MANAGE 4.1', 'ISO/IEC 42001 A.6.2'],
},
{
  slug: 'osp-11', code: 'OSP-11', name: 'Human-Agent Trust Exploitation', order: 13, scope: 'secondary',
  behaviour: 'The agent presents a misleading summary or a confident recommendation that causes a human to approve something they would otherwise refuse. The failure lands on the human, not the machine.',
  signals: [
    'Mismatch between the agent’s summary text and its executed actions',
    'Approval requests framed with urgency',
    'Evidence links that do not resolve to the cited source',
    'Confidence language unsupported by the grounding actually retrieved',
  ],
  severity: 'medium',
  harmClasses: ['societal', 'operational'],
  action: { peak: 'review', summary: 'Review. The MOM Assistant must show the executed action alongside the agent’s summary so the reviewer compares both.', tier: 'HOTL', humanReview: 'always', reviewNote: 'Required by design. This category is a dashboard requirement rather than a runtime block — the human is the control, not a fallback.' },
  detection: { instrument: 'hybrid', method: 'Mechanical summary-versus-action comparison, model judges materiality', slmDifficulty: 'hard',
    rationale: 'Comparing what the agent said it did against what it actually did is mechanical. Judging whether the gap is material is the model’s part, and labelled examples barely exist.',
    inGate1: false, dependsOn: ['Agent summary text captured alongside the action trace'] },
  evidence: ['Output labelling and action attribution records (AGSC ALN-05)', 'Governance review inputs (ADG MC-10)'],
  anchors: [
    a('agsc', 'ALN-05', 'Output Labeling & Action Attribution', 'Attribution is what lets a reviewer see the gap between claim and action.'),
    a('agsc', 'SAF-04', 'Output Factual Accuracy & Anti-Hallucination', 'A confident, unsupported recommendation is the failure this control names.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Detecting the mismatch is monitoring work.'),
    a('adg', 'MC-10', 'Periodic Governance Review', 'Patterns of misleading approval requests belong in the review.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM07', 'Misinformation', 'Overreliance and unsupported decision support: humans treating fluent output as authoritative.'),
    a('owasp-asi', 'ASI09', 'Human-Agent Trust Exploitation', 'The direct agentic counterpart.'),
    { framework: 'mitre-atlas', id: 'AML.T0100 / T0052.001', label: 'Agent-driven social engineering entries',
      weight: 'supporting', verification: 'pending',
      rationale: 'Identifiers carried from an earlier revision and not re-confirmed in the latest validation pass.' },
  ],
  regulatory: ['EU AI Act Art. 13, 14, 50', 'NIST AI RMF GOVERN 1; MEASURE 2.9', 'ISO/IEC 42001 A.8'],
},
{
  slug: 'osp-12', code: 'OSP-12', name: 'Supply Chain & Tool Integrity', order: 14, scope: 'secondary',
  behaviour: 'A tool, MCP server, model or schema the agent depends on is swapped, poisoned, or silently changed. The agent behaves correctly against a component that is no longer trustworthy.',
  signals: [
    'Tool schema or endpoint changes between sessions',
    'Unsigned or newly published tool versions',
    'A tool’s described behaviour diverging from its observed behaviour',
    'Registry reputation shifts',
    'An unexpected model or adapter version at inference time',
  ],
  severity: 'high',
  harmClasses: ['technical', 'systemic'],
  harmNote: 'Systemic because every agent depending on the component inherits the compromise at once.',
  action: { peak: 'block', summary: 'Block and alert. Handled primarily at the Harness deployment gate rather than at runtime.', tier: 'HITL', humanReview: 'always', reviewNote: 'Required to approve any changed component before it re-enters the pipeline.' },
  detection: { instrument: 'deterministic', method: 'Registry diff and signature check between runs', slmDifficulty: null,
    rationale: 'Deployment-gate territory. Comparing tool schemas, versions and signatures between runs is deterministic, and belongs in the CI/CD gate rather than in the runtime classifier.',
    inGate1: false, dependsOn: ['Component registry with signatures', 'Per-run component manifest'] },
  evidence: ['Third-party component register and change approvals (AGSC GOV-03, GOV-07)', 'Tool and MCP register with approval status (ADG MC-7)'],
  anchors: [
    a('agsc', 'GOV-03', 'Third-Party & Supply-Chain Oversight', 'External components changing without assessment is the failure this control prevents.'),
    a('agsc', 'GOV-01', 'Data Provenance & Input Integrity', 'A poisoned tool is a compromised input source.', 'verified', 'supporting'),
    a('agsc', 'GOV-07', 'AI Lifecycle & Registry Management', 'The registry is what an observed component is compared against.', 'verified', 'supporting'),
    a('adg', 'MC-7', 'Tool and MCP Register', 'Trust tiering and third-party assurance status map one-to-one onto this label.'),
    a('adg', 'MC-5', 'Change Control', 'An unapproved component change is a change-control failure seen at runtime.'),
    a('adg', 'MC-12', 'Shared Responsibility Documentation', 'A vendor component changing triggers a responsibility-matrix review.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM04', 'Supply Chain', 'Model artifacts, provenance and conversion workflows as first-class attack surfaces.'),
    a('owasp-llm', 'LLM05', 'Data and Model Poisoning', 'Malicious models distributed through public repositories.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI04', 'Agentic Supply Chain Vulnerabilities', 'The entry OWASP LLM04 explicitly defers agentic supply-chain risk to, covering MCP servers and tool registries.'),
    a('mitre-atlas', 'AML.T0010', 'AI Supply Chain Compromise', 'Cited by OWASP LLM04:2026 as the corresponding adversary technique.'),
    a('mitre-atlas', 'AML.T0110', 'AI Agent Tool Poisoning', 'A tool the agent trusts turned against it.'),
    a('mitre-atlas', 'AML.T0018', 'Manipulate AI Model', 'Backdoored or tampered model artifacts.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 25', 'NIST AI RMF GOVERN 6.1', 'ISO/IEC 42001 A.10'],
},
{
  slug: 'osp-15', code: 'OSP-15', name: 'Hidden Context & Instruction Exposure', order: 15, scope: 'secondary', addedIn: 'v1.0',
  behaviour: 'The agent’s own control layer leaks. System prompt, tool schemas, policy logic, trust boundaries or workflow criteria are extracted, inferred or reconstructed, handing an attacker the map they need to attack everything else.',
  signals: [
    'Outputs quoting or paraphrasing system-prompt text',
    'Tool or function schemas appearing in responses',
    'Probing sequences that enumerate capabilities',
    'Responses describing internal policy thresholds',
    'Repeated near-miss requests whose phrasing shifts after each refusal',
  ],
  severity: 'medium',
  severityNote: 'High where hidden context holds credentials or where the application relies on its secrecy to gate authorization.',
  harmClasses: ['technical'],
  harmNote: 'An enabler rather than an endpoint: the damage is what it makes possible next.',
  action: { peak: 'block', summary: 'Block the disclosing output and log. Treat a detection as a trigger to re-check whether anything security-relevant is sitting in the context at all.', tier: 'HOTL', humanReview: 'conditional', reviewNote: 'No human needed for the block. A governance review is triggered if the exposed context turns out to gate an authorization decision.' },
  detection: { instrument: 'hybrid', method: 'Similarity check against known hidden context, SLM classifier for paraphrase and inference', slmDifficulty: 'easy-medium',
    rationale: 'Verbatim leakage is a similarity comparison against a string the platform already holds — cheap and exact. The model earns its place on paraphrase and inference. Synthetic data is easy to generate, which makes this the second most likely label to reach its accuracy target.',
    inGate1: true, dependsOn: ['Access to the assembled system context for comparison'] },
  evidence: ['Context-boundary decisions and blocked-disclosure records (AGSC SEC-07)', 'Context policy review evidence (ADG MC-6)'],
  anchors: [
    a('agsc', 'SEC-07', 'Memory & Context Lifecycle Security', 'Hidden context is context, and its boundary is this control’s concern.'),
    a('agsc', 'SEC-03', 'Prompt Injection & Adversarial Input Defense', 'Extraction attempts arrive through the same ingestion points as injection.', 'verified', 'supporting'),
    a('agsc', 'SAF-05', 'AI Output Monitoring & Safeguards', 'Blocking the disclosing output.', 'verified', 'supporting'),
    a('adg', 'MC-6', 'Context Policy', 'What may sit in hidden context, and what may never, is a context-policy decision.'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Data leakage in production is named in scope.'),
    a('owasp-llm', 'LLM08', 'Hidden Context Exposure', 'The 2026 re-scoping of System Prompt Leakage into a broader failure to keep control context out of reach.'),
    a('owasp-asi', 'ASI06', 'Memory & Context Poisoning', 'Named by LLM08 as the pointer for persistent-memory amplification of this risk.', 'verified', 'supporting'),
    a('owasp-asi', 'ASI07', 'Insecure Inter-Agent Communication', 'Named by LLM08 as the pointer for hidden context propagating across agent channels.', 'verified', 'supporting'),
    a('mitre-atlas', 'AML.TA0008', 'Discovery', 'Enumerating capabilities and policy logic.'),
    a('mitre-atlas', 'AML.TA0010', 'Exfiltration', 'Moving that control context out of the system.', 'verified', 'supporting'),
  ],
  regulatory: ['EU AI Act Art. 15', 'NIST AI RMF MEASURE 2.7', 'ISO/IEC 42001 A.6.2'],
},
{
  slug: 'osp-16', code: 'OSP-16', name: 'Fabricated Completion & Evidence', order: 16, scope: 'secondary', addedIn: 'v1.0',
  behaviour: 'The agent reports work it did not do, or produces evidence for a result it never reached. Distinct from drift: the trajectory can look clean while the final claim is false.',
  signals: [
    'Completion claims with no corresponding tool call or write in the trace',
    'Cited artifacts that do not exist or do not contain the cited content',
    'Success reported after a failed or errored call',
    'Summaries naming entities that appear nowhere in the retrieved context',
  ],
  severity: 'medium-high',
  harmClasses: ['operational', 'systemic'],
  harmNote: 'Systemic once downstream agents or workflows treat the false completion as a satisfied precondition.',
  action: { peak: 'review', summary: 'Review. Block the completion signal from propagating downstream until the trace supports the claim.', tier: 'HOTL', humanReview: 'conditional', reviewNote: 'HOTL by default. HITL where the completion gates an irreversible downstream action.' },
  detection: { instrument: 'hybrid', method: 'Trace reconciliation against the completion claim, model judges materiality', slmDifficulty: 'hard',
    rationale: 'Reconciling a claim against the trace is mechanical once the trace is complete: did a write happen, does the cited artifact exist. What the model adds is judging whether an unsupported claim is material. Labelled data is effectively non-existent today, so this starts as a rule and a dashboard column.',
    inGate1: false, dependsOn: ['Complete action trace per session', 'Artifact existence check'] },
  evidence: ['Claim-versus-trace reconciliation records (AGSC SAF-04)', 'Forensic replay material (ADG MC-9)'],
  anchors: [
    a('agsc', 'SAF-04', 'Output Factual Accuracy & Anti-Hallucination', 'A fabricated completion is a fact-bearing output with no grounding.'),
    a('agsc', 'ALN-05', 'Output Labeling & Action Attribution', 'Attribution is what makes the reconciliation possible.'),
    a('agsc', 'SAF-01', 'Autonomous System Oversight', 'Reported success that did not occur is precisely the failure oversight exists to catch.', 'verified', 'supporting'),
    a('adg', 'MC-8', 'Runtime Monitoring', 'Detecting the claim-trace gap.'),
    a('adg', 'MC-9', 'AI Incident Response', 'Forensic replay is what proves the claim was false.', 'verified', 'supporting'),
    a('owasp-llm', 'LLM07', 'Misinformation', 'Forged or misattributed evidence, and fabricated task completion, are named risk examples in the 2026 entry.'),
    a('owasp-asi', 'ASI10', 'Rogue Agents', 'An agent that falsifies task completion to mislead downstream trust.'),
    { framework: 'mitre-atlas', id: '—', label: 'Falsified task completion', weight: 'primary', verification: 'gap',
      rationale: 'No published ATLAS technique models an agent misreporting its own work. The AGSC and ADG controls carry this row on their own.' },
  ],
  regulatory: ['EU AI Act Art. 13, 15', 'NIST AI RMF MEASURE 2.3, 2.9', 'ISO/IEC 42001 A.8'],
},
];

for (const { slug, ...rest } of T) {
  writeFileSync(join(ROOT, `${slug}.yaml`), yaml(rest) + '\n', 'utf8');
}
console.log(`seeded ${T.length} threats`);
